"""initial schema

Revision ID: 8d1a326f879a
Revises: 
Create Date: 2026-09-19 23:44:53.656785
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '8d1a326f879a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('name_rejects',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('reason', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('players',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('secret_hash', sa.LargeBinary(length=32), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('name_set_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('h2h_matches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=True),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('player_a', sa.UUID(), nullable=False),
    sa.Column('player_b', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('winner', sa.UUID(), nullable=True),
    sa.Column('end_reason', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("kind IN ('room','queue')", name='ck_match_kind'),
    sa.CheckConstraint("status IN ('waiting','placing','playing','finished','abandoned')", name='ck_match_status'),
    sa.ForeignKeyConstraint(['player_a'], ['players.id'], ),
    sa.ForeignKeyConstraint(['player_b'], ['players.id'], ),
    sa.ForeignKeyConstraint(['winner'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('game_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('client_game_id', sa.UUID(), nullable=False),
    sa.Column('mode', sa.String(length=4), nullable=False),
    sa.Column('match_id', sa.UUID(), nullable=True),
    sa.Column('attacker_kind', sa.String(length=10), nullable=False),
    sa.Column('attacker_player', sa.UUID(), nullable=True),
    sa.Column('attacker_label', sa.Text(), nullable=False),
    sa.Column('defender_player', sa.UUID(), nullable=True),
    sa.Column('ships', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('shots', sa.ARRAY(sa.SmallInteger()), nullable=False),
    sa.Column('n_shots', sa.SmallInteger(), nullable=False),
    sa.Column('fleet_cleared', sa.Boolean(), nullable=False),
    sa.Column('won', sa.Boolean(), nullable=True),
    sa.Column('client', sa.String(length=16), nullable=False),
    sa.Column('client_version', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("attacker_kind IN ('player','model','heuristic')", name='ck_game_log_attacker_kind'),
    sa.CheckConstraint("mode IN ('h2m','h2h')", name='ck_game_log_mode'),
    sa.ForeignKeyConstraint(['attacker_player'], ['players.id'], ),
    sa.ForeignKeyConstraint(['defender_player'], ['players.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['h2h_matches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_game_id', 'attacker_label', name='uq_game_log_client_attacker')
    )
    op.create_index('ix_game_logs_attacker_created', 'game_logs', ['attacker_player', 'created_at'], unique=False)
    op.create_index('ix_game_logs_mode_cleared', 'game_logs', ['mode', 'fleet_cleared'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_game_logs_mode_cleared', table_name='game_logs')
    op.drop_index('ix_game_logs_attacker_created', table_name='game_logs')
    op.drop_table('game_logs')
    op.drop_table('h2h_matches')
    op.drop_table('players')
    op.drop_table('name_rejects')
    # ### end Alembic commands ###
